### ISSUE TITLE
After using the plugin, the folder cannot change colors

### ISSUE THREAD

**Issue by zhangchaoyanggit** [AtomMaterialUI/material-theme-ui-lite#189]
idea.version: 2023.3
mac m1 
<img width="624" alt="image" src="https://github.com/AtomMaterialUI/material-theme-ui-lite/assets/24430480/a8231e8e-f3b5-41a6-aecc-c46da9fe68c3">

I like the color in your screenshot

<img width="703" alt="image" src="https://github.com/AtomMaterialUI/material-theme-ui-lite/assets/24430480/a7e2d90f-936b-4b00-bdce-f7a7b58ccbbd">

**Comment by mallowigi** [comment]
I don't understand. In your first screenshot it looks like the plugin is not working at all. Did you see an error in the plugins page?

**Comment by mallowigi** [comment]
And what's the relation with the folders?

**Comment by zhangchaoyanggit** [comment]
sorry, This is the effect after I installed it
<img width="1299" alt="image" src="https://github.com/AtomMaterialUI/material-theme-ui-lite/assets/24430480/f2d6bf9a-a229-4f00-a852-3c172787ec03">

But I want the following effect
<img width="907" alt="image" src="https://github.com/AtomMaterialUI/material-theme-ui-lite/assets/24430480/b0bec437-10f1-4e7c-8533-e17af313a805">

**Comment by mallowigi** [comment]
And what is the problem? The screenshot shows the Arc Dark theme
